### ISSUE TITLE
Error in SCA import when bad appli URL

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#14]
Step to reproduce :
- create new appli with root service URL http://localhost:9000S
- import SmartTravel SCA file, it fails with the following logs :

2011-07-20 17:39:25,288 ERROR [org.easysoa.sca.ScaImporter] Error when visiting binding org.easysoa.sca.visitors.WSBindingScaVisitor@12011a7 at archi path /trip in SCA composite file smart-travel-mock-services.composite
java.net.MalformedURLException: For input string: "9000S"
    at java.net.URL.<init>(Unknown Source)
    at java.net.URL.<init>(Unknown Source)
    at java.net.URL.<init>(Unknown Source)
    at org.easysoa.doctypes.PropertyNormalizer.normalizeUrl(PropertyNormalizer.java:35)
    at org.easysoa.services.NotificationService.computeApiUrl(NotificationService.java:293)
    at org.easysoa.sca.visitors.ServiceBindingVisitorBase.visit(ServiceBindingVisitorBase.java:41)
    at org.easysoa.sca.ScaImporter.acceptBindingVisitors(ScaImporter.java:201)
    at org.easysoa.sca.ScaImporter.acceptBindingParentVisitors(ScaImporter.java:190)
    at org.easysoa.sca.ScaImporter.importSCA(ScaImporter.java:129)
...
2011-07-20 17:39:25,292 ERROR [org.easysoa.sca.ScaImportBean] Failed to import SCA
java.lang.NullPointerException
    at org.easysoa.sca.visitors.ReferenceBindingVisitorBase.getDescription(ReferenceBindingVisitorBase.java:35)
    at org.easysoa.sca.ScaImporter.acceptBindingVisitors(ScaImporter.java:204)
    at org.easysoa.sca.ScaImporter.acceptBindingParentVisitors(ScaImporter.java:190)
    at org.easysoa.sca.ScaImporter.importSCA(ScaImporter.java:136)
...

To patch it, check appli URL (and others) with new URL(...) when first entered by the user.

**Comment by mkalam-alami** [comment]
The document forms now validate the URLs before to save.
