### ISSUE TITLE
BUG still dependencies on online services and WSDLs

### ISSUE THREAD

**Issue by mdutoo** [easysoa/EasySOA#48]
Redo all tuto & demoes without internet to be sure.
- in 0.2 demo (but using 20110929 registry and scaffoldingProxy), travel backup still refers to online wsdls, error message at startup :

in travelBackup, start-travelBackup.bat :

---

Travel services backup
## (Deployed on http://localhost:9020)

Starting Server
5 oct. 2011 19:17:10 org.apache.cxf.service.factory.ReflectionServiceFactoryBean buildServiceFromClass
INFO: Creating Service {http://www.webserviceX.NET}GlobalWeather from class net.webservicex.GlobalWeatherSoap
5 oct. 2011 19:17:11 org.apache.cxf.endpoint.ServerImpl initDestination
INFO: Setting the server's publish address to be http://localhost:9020/WeatherService
6 [main] INFO org.eclipse.jetty.util.log - jetty-7.3.1.v20110307
92 [main] INFO org.eclipse.jetty.util.log - Started SelectChannelConnector@localhost:9020
119 [main] INFO org.eclipse.jetty.util.log - started o.e.j.s.h.ContextHandler{,null}
5 oct. 2011 19:17:11 org.apache.cxf.service.factory.ReflectionServiceFactoryBean buildServiceFromWSDL
INFO: Creating Service {http://www.daenet.de/webservices/CurrencyServer}CurrencyServerWebService from WSDL: http://www.currencyserver.de/webservice/currencyserverwebservice.asmx?wsdl
Exception in thread "main" javax.xml.ws.WebServiceException: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
        at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:350)
        at org.apache.cxf.jaxws.EndpointImpl.publish(EndpointImpl.java:239)
        at org.apache.cxf.jaxws.spi.ProviderImpl.createAndPublishEndpoint(ProviderImpl.java:144)
        at javax.xml.ws.Endpoint.publish(Unknown Source)
        at net.server.Server.<init>(Server.java:33)
        at net.server.Server.main(Server.java:47)
Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Failed to create service.
        at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:93)
        at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.buildServiceFromWSDL(ReflectionServiceFactoryBean.java:369)
        at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:499)
        at org.apache.cxf.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:241)
        at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:202)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:101)
        at org.apache.cxf.frontend.ServerFactoryBean.create(ServerFactoryBean.java:157)
        at org.apache.cxf.jaxws.JaxWsServerFactoryBean.create(JaxWsServerFactoryBean.java:192)
        at org.apache.cxf.jaxws.EndpointImpl.getServer(EndpointImpl.java:433)
        at org.apache.cxf.jaxws.EndpointImpl.doPublish(EndpointImpl.java:322)
        ... 5 more
Caused by: javax.wsdl.WSDLException: WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://www.currencyserver.de/webservice/currencyserverwebservice.asmx?wsdl'.: java.net.UnknownHostException: www.currencyserver.de
        at com.ibm.wsdl.xml.WSDLReaderImpl.getDocument(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at com.ibm.wsdl.xml.WSDLReaderImpl.readWSDL(Unknown Source)
        at org.apache.cxf.wsdl11.WSDLManagerImpl.loadDefinition(WSDLManagerImpl.java:239)
        at org.apache.cxf.wsdl11.WSDLManagerImpl.getDefinition(WSDLManagerImpl.java:186)
        at org.apache.cxf.wsdl11.WSDLServiceFactory.<init>(WSDLServiceFactory.java:91)
        ... 14 more
Caused by: java.net.UnknownHostException: www.currencyserver.de

**Comment by JGuillemotte** [comment]
Resolved. I have removed the attributes wsdlLocation in the currency web service mock classes. It can now works without to have an Internet access.
